version: '3.8'

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      APPLICATION_PORT: ${APPLICATION_PORT}
      URL: ${URL}
      DIALECT: ${DIALECT}
      DB_USERNAME: ${DB_USERNAME}
      DATABASE: ${DATABASE}
      PASSWORD: ${PASSWORD}
      HOST: database
      DB_PORT: ${DB_PORT}
      TOKEN_SECRET: ${TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"

volumes:
  postgres_data:
