openapi: 3.0.0
info:
  title: API Documentação
  description: Esta é a documentação da API gerada automaticamente.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
